
export const HOME_PAGE_NOT_STARTED = "HOME_PAGE_NOT_STARTED"
export const HOME_PAGE_FETCHING_INIT_DATA = "HOME_PAGE_FETCHING_INIT_DATA"
export const HOME_PAGE_SHOWING_ERROR = "HOME_PAGE_SHOWING_ERROR"
export const HOME_PAGE_READY = "HOME_PAGE_READY"