export const HOME_PAGE_NOT_STARTED = "HOME_PAGE_NOT_STARTED"
export const HOME_PAGE_FETCHING_INIT_DATA = "HOME_PAGE_FETCHING_INIT_DATA"
export const HOME_PAGE_SHOWING_ERROR = "HOME_PAGE_SHOWING_ERROR"
export const HOME_PAGE_READY = "HOME_PAGE_READY"

export const LOGIN_PAGE_NOT_STARTED = "LOGIN_PAGE_NOT_STARTED"
export const LOGIN_PAGE_READY = "LOGIN_PAGE_READY"
export const LOGIN_PAGE_SHOWING_ERRORS = "LOGIN_PAGE_SHOWING_ERRORS"
export const LOGIN_PAGE_WAITING = "LOGIN_PAGE_WAITING"

export const PRODUCT_ADD_NOT_STARTED = "PRODUCT_ADD_NOT_STARTED"
export const PRODUCT_ADD_READY = "PRODUCT_ADD_READY"
export const PRODUCT_ADD_SHOWING_ERRORS = "PRODUCT_ADD_SHOWING_ERRORS"
export const PRODUCT_ADD_WAITING = "PRODUCT_ADD_WAITING"

export const PRODUCT_EDIT_NOT_STARTED = "PRODUCT_EDIT_NOT_STARTED"
export const PRODUCT_EDIT_READY = "PRODUCT_EDIT_READY"
export const PRODUCT_EDIT_SHOWING_ERRORS = "PRODUCT_EDIT_SHOWING_ERRORS"
export const PRODUCT_EDIT_WAITING = "PRODUCT_EDIT_WAITING"