export const LOAD_APP = "LOAD_APP"
export const LOGOUT = "LOGOUT"

export const VISIT_HOME_PAGE = "VISIT_HOME_PAGE"
export const VISIT_LOGIN_PAGE = "VISIT_LOGIN_PAGE"
export const VISIT_CART_PAGE = "VISIT_CART_PAGE"
export const VISIT_CHECKOUT_PAGE = "VISIT_CHECKOUT_PAGE"
export const VISIT_PRODUCT_VIEW_PAGE = "VISIT_PRODUCT_VIEW_PAGE"
export const VISIT_PRODUCT_EDIT_PAGE = "VISIT_PRODUCT_EDIT_PAGE"
export const VISIT_PRODUCT_ADD_PAGE = "VISIT_PRODUCT_ADD_PAGE"
export const VISIT_PRODUCT_DELETE_PAGE = "VISIT_PRODUCT_DELETE_PAGE"

export const ENTER_HOME_PAGE = "ENTER_HOME_PAGE"
export const EXIT_HOME_PAGE = "EXIT_HOME_PAGE"

export const ENTER_LOGIN_PAGE = "ENTER_LOGIN_PAGE"
export const EXIT_LOGIN_PAGE = "EXIT_LOGIN_PAGE"

export const ENTER_PRODUCT_ADD_PAGE = "ENTER_PRODUCT_ADD_PAGE"
export const EXIT_PRODUCT_ADD_PAGE = "EXIT_PRODUCT_ADD_PAGE"

export const ENTER_PRODUCT_EDIT_PAGE = "ENTER_PRODUCT_EDIT_PAGE"
export const EXIT_PRODUCT_EDIT_PAGE = "EXIT_PRODUCT_EDIT_PAGE"

export const FETCH_INIT_HOME_PAGE_DATA = "FETCH_INIT_HOME_PAGE_DATA"
export const RECEIVE_INIT_HOME_PAGE_DATA = "RECEIVE_INIT_HOME_PAGE_DATA"
export const RECEIVE_INIT_HOME_PAGE_ERROR = "RECEIVE_INIT_HOME_PAGE_ERROR"

export const CHANGE_USERNAME = "CHANGE_USERNAME"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"

export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const PREPARE_LOGIN_REQUEST = "PREPARE_LOGIN_REQUEST"
export const RECEIVE_LOGIN_OK_DATA = "RECEIVE_LOGIN_OK_DATA"
export const RECEIVE_LOGIN_DENIED_DATA = "RECEIVE_LOGIN_DENIED_DATA"
export const RECEIVE_LOGIN_ERROR = "RECEIVE_LOGIN_ERROR"

export const CHANGE_PRODUCT_ADD_FIELD = "CHANGE_PRODUCT_ADD_FIELD"
export const CHANGE_PRODUCT_EDIT_FIELD = "CHANGE_PRODUCT_EDIT_FIELD"

export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT"
export const PREPARE_ADD_PRODUCT_REQUEST = "PREPARE_ADD_PRODUCT_REQUEST"
export const RECEIVE_ADD_PRODUCT_OK_DATA = "RECEIVE_ADD_PRODUCT_OK_DATA"
export const RECEIVE_ADD_PRODUCT_ERROR_DATA = "RECEIVE_ADD_PRODUCT_ERROR_DATA"

export const FETCH_INIT_EDIT_PRODUCT_PAGE_DATA = "FETCH_INIT_EDIT_PRODUCT_PAGE_DATA"
export const RECEIVE_INIT_EDIT_PRODUCT_PAGE_DATA = "RECEIVE_INIT_EDIT_PRODUCT_PAGE_DATA"
export const RECEIVE_INIT_EDIT_PRODUCT_PAGE_ERROR = "RECEIVE_INIT_EDIT_PRODUCT_PAGE_ERROR"

export const REQUEST_EDIT_PRODUCT = "REQUEST_EDIT_PRODUCT"
export const PREPARE_EDIT_PRODUCT_REQUEST = "PREPARE_EDIT_PRODUCT_REQUEST"
export const RECEIVE_EDIT_PRODUCT_OK_DATA = "RECEIVE_EDIT_PRODUCT_OK_DATA"
export const RECEIVE_EDIT_PRODUCT_ERROR_DATA = "RECEIVE_EDIT_PRODUCT_ERROR_DATA"

export const EDIT_PRODUCT = "EDIT_PRODUCT"