export const LOAD_APP = "LOAD_APP"

export const VISIT_HOME_PAGE = "VISIT_HOME_PAGE"
export const VISIT_LOGIN_PAGE = "VISIT_LOGIN_PAGE"
export const VISIT_CART_PAGE = "VISIT_CART_PAGE"
export const VISIT_CHECKOUT_PAGE = "VISIT_CHECKOUT_PAGE"
export const VISIT_PRODUCT_VIEW_PAGE = "VISIT_PRODUCT_VIEW_PAGE"
export const VISIT_PRODUCT_EDIT_PAGE = "VISIT_PRODUCT_EDIT_PAGE"
export const VISIT_PRODUCT_ADD_PAGE = "VISIT_PRODUCT_ADD_PAGE"
export const VISIT_PRODUCT_DELETE_PAGE = "VISIT_PRODUCT_DELETE_PAGE"

export const ENTER_HOME_PAGE = "ENTER_HOME_PAGE"
export const LEAVE_HOME_PAGE = "LEAVE_HOME_PAGE"

export const FETCH_INIT_HOME_PAGE_DATA = "FETCH_INIT_HOME_PAGE_DATA"
export const RECEIVE_INIT_HOME_PAGE_DATA = "RECIEVE_INIT_HOME_PAGE_DATA"
export const RECEIVE_INIT_HOME_PAGE_ERROR = "RECIEVE_INIT_HOEM_PAGE_ERROR"

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
