export const HOME_PAGE = "HOME_PAGE";
export const LOGIN_PAGE = "LOGIN_PAGE";
export const CART_PAGE = "CART_PAGE";
export const CHECKOUT_PAGE = "CHECKOUT_PAGE";
export const PRODUCT_VIEW_PAGE = "PRODUCT_VIEW_PAGE";
export const PRODUCT_ADD_PAGE = "PRODUCT_ADD_PAGE";
export const PRODUCT_EDIT_PAGE = "PRODUCT_EDIT_PAGE";
export const PRODUCT_DELETE_PAGE = "PRODUCT_DELETE_PAGE";